plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# supported Themes: https://pages.github.com/themes/
remote_theme: pages-themes/merlot@v0.2.0
# remote_theme: pages-themes/modernist@v0.2.0
# remote_theme: pages-themes/architect@v0.2.0

# theme: jekyll-theme-minimal

title: [The title of your site]
description: Bookmark this to keep an eye on my project updates!

# to preview your site on your computer, add the following to your site's Gemfile:
# gem "github-pages", group: :jekyll_plugins

# show_downloads: ["true" or "false" (unquoted) to indicate whether to provide a download URL]

# google_analytics: [Your Google Analytics tracking ID]